### ISSUE TITLE
GPS is not working

### ISSUE THREAD

**Issue by griswaldbrooks** [victoriarobotics/victoria_navigation#8]
Despite @markwomack getting the GPS working last night, this afternoon I was unable to get a fix either with the external antenna nor the onboard patch antenna.

**Comment by griswaldbrooks** [comment]
Note, I did not try the onboard patch antenna with the cover off.

**Comment by markwomack** [comment]
This is worrisome. I think I will order a backup today.

**Comment by markwomack** [comment]
Adafruit GPS is out of stock.  @mwimble - Is this the Sparkfun version that you mentioned?

https://www.sparkfun.com/products/11058

It would be a pretty good "drop in" replacement maybe.

**Comment by mwimble** [comment]
Yes, I think it is.

**Comment by griswaldbrooks** [comment]
One of my mangers who used to do drone work, suggested the ublox M8, which I could get by tomorrow in this package:
https://www.amazon.com/Readytosky-NEO-M8N-HMC5883L-Protective-Controller/dp/B01KK9A8QG/ref=sr_1_1?ie=UTF8&qid=1490908789&sr=8-1&keywords=ublox

Thoughts?

**Comment by griswaldbrooks** [comment]
He's personally used the chip and says it gets fast locks and has great accuracy.

**Comment by mwimble** [comment]
Ordered one myself.

**Comment by griswaldbrooks** [comment]
The M8N?

**Comment by markwomack** [comment]
I ordered an M8 to play with.  It will get here Saturday...which won't help much for this weekend.

**Comment by griswaldbrooks** [comment]
Should I get one too? If I have it tomorrow I can try it out.

**Comment by griswaldbrooks** [comment]
So it looks like that second connector is a I2C for the compass.

**Comment by markwomack** [comment]
Go for it.

**Comment by mwimble** [comment]
Yes. Should also be here Friday.

**Comment by mwimble** [comment]
Yes.

**Comment by griswaldbrooks** [comment]
Ok, so Saturday it will be here :(

**Comment by griswaldbrooks** [comment]
Saturday it did not show up so I ordered another.

**Comment by mwimble** [comment]
Is there any data on the compass? How to talk to it?

**Comment by griswaldbrooks** [comment]
I haven't looked into it but it claims compatibility with the pixhawk. Did you get yours?

**Comment by mwimble** [comment]
Yep, see other message just sent.

**Comment by griswaldbrooks** [comment]
New GPS works, after the mast was built to move it from the camera and orient it upwards.
